version: "3.7"
services:
  api_service:
    build: .
    restart: always
    networks:
      - springapimysql-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/tourisme_alternative?allowPublicKeyRetrieval=true
    depends_on:
      - mysqldb
    volumes:
      - .m2:/root/.m2

  mysqldb:
    image: "mysql:8.0"
    restart: always
    networks:
      - springapimysql-net
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: tourisme_alternative
    volumes:
      - tourism_alternative_db_data:/var/lib/mysql

  react-app:
    build: ./../toursim_front
    restart: always
    ports:
      - 81:80
    networks:
      - springapimysql-net
    depends_on:
      - api_service

networks:
  springapimysql-net:

volumes:
  tourism_alternative_db_data:

