spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tourisme_alternative
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.MySQL5Dialect

