spring:
  devtools:
    restart:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/tourisme_alternative
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: false
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 629253409154-sdg7icilei8rkvaj5503mb3gcepcq97n.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
          facebook:
            clientId: 993666651618691
            clientSecret: f3e8bfadb098978e0d80b0371adb13e0
            scope:
              - email
              - public_profile
              - user_birthday
              - user_posts
cors:
  allowed:
    origins=*:
flickr:
  apiKey: 388b4a070b8943c7b1878ba9fd2e9f77
  apiSecret: 5604a75bcef0767f
  appKey: 72157720878005563-289b4c10e2c8792c
  appSecret: 1b53a3d49f62a84d